[versions]
#convention
domain = "com.tezov"
name = "tuucho"
versionCode = "1"
versionName = "0.0.1-alpha23_2.2.21"
isSnapshot = "false"
javaVersion = "17"
minSdk = "24"
compileSdk = "36"
ktlintRules = "1.7.1"
detektRules = "1.23.8"

#plugin
android-plugin = "8.13.1"
kotlin-plugin = "2.2.21"
compose-plugin = "1.9.3"
kotlin-serialization-plugin = "2.2.21"
maven-plugin = "0.35.0"
ktlint = "14.0.1"
detekt = "1.23.8"

#lib - platform
kotlin-couroutine = "1.10.2"
kotlin-serialization-json = "1.9.0"
kotlin-collections-immutable = "0.4.0"
sql-delight = "2.2.1"
ktor = "3.3.3"
koin = "4.2.0-alpha3"
kotlin-datetime = "0.7.1"
okio = "3.16.4"

#lib - android
compose-activity = "1.12.0"
compose-backhandler= "1.9.3"
datastore-preferences = "1.2.0"

#test
jacoco = "0.8.13"
mokkery = "3.0.0"

[libraries]
#build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
maven = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-plugin" }
ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
#compose - android
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
#lib - platform
kotlin-couroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-couroutine" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
sql-delight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sql-delight" }
sql-delight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sql-delight" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlin-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
#lib - android
sql-delight-driver-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sql-delight" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
compose-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "compose-backhandler" }
#lib - ios
sql-delight-driver-ios = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sql-delight" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
#test
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-couroutine" }
mokkery = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
all-open = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin-plugin" }

[plugins]
#convention
convention-maven = { id = "com.tezov.tuucho.convention.project.maven", version = "" }
convention-library-test = { id = "com.tezov.tuucho.convention.project.library-test", version = "" }
convention-library-plain = { id = "com.tezov.tuucho.convention.project.library-plain", version = "" }
convention-library-ui = { id = "com.tezov.tuucho.convention.project.library-ui", version = "" }
#convention
maven = { id = "maven-publish", version = "" }
signing = { id = "signing", version = "" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-plugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
sql-delight = { id = "app.cash.sqldelight", version.ref = "sql-delight" }
#test
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
all-open = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin-plugin" }

