[versions]
#convention
domain = "com.tezov"
name = "tuucho"
versionCode = "1"
versionName = "0.0.1-alpha29_2.3.20-Beta2"
isSnapshot = "false"
javaVersion = "17"
minSdk = "24"
compileSdk = "36"
ktlintRules = "1.7.1"
detektRules = "1.23.8"

#plugin
android-plugin = "9.0.0"
kotlin-plugin = "2.3.20-Beta2"
koin-plugin = "0.3.0"
compose-plugin = "1.10.0"
kotlin-serialization-plugin = "2.3.0"
maven-plugin = "0.36.0"
ktlint-plugin = "14.0.1"
detekt-plugin = "1.23.8"

#lib - platform
kotlin-couroutine = "1.10.2"
kotlin-serialization-json = "1.10.0"
kotlin-collections-immutable = "0.4.0"
sql-delight = "2.2.1"
ktor = "3.4.0"
koin = "4.2.0-RC1"
kotlin-datetime = "0.7.1"
okio = "3.16.4"
coil = "3.3.0"
compose = "1.10.0"
compose-material3 = "1.9.0"

#lib - android
compose-navigationevent = "1.0.0"
compose-ui-tooling = "1.10.0"
datastore-preferences = "1.2.0"

#test
jacoco = "0.8.14"
mokkery = "3.1.1"

[libraries]
#build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
kotlin-multiplatform-gradle-plugin = { group = "org.jetbrains.kotlin.multiplatform", name = "org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin-plugin" }
maven = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "maven-plugin" }
ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-plugin" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt-plugin" }
#lib - platform
kotlin-couroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-couroutine" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
sql-delight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sql-delight" }
sql-delight-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sql-delight" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-cio = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
kotlin-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core", version.ref = "coil" }
coil-compose-core = { group = "io.coil-kt.coil3", name = "coil-compose-core", version.ref = "coil" }
compose-runtime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "compose" }
compose-foundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "compose" }
compose-ui = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "compose" }
compose-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "compose-material3" }
#lib - android
sql-delight-driver-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sql-delight" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }
compose-navigationevent = { group = "org.jetbrains.androidx.navigationevent", name = "navigationevent-compose", version.ref = "compose-navigationevent" }
compose-ui-tooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "compose-ui-tooling" }
compose-ui-tooling-preview = { group = "org.jetbrains.compose.components", name = "components-ui-tooling-preview", version.ref = "compose-ui-tooling" }

#lib - ios
sql-delight-driver-ios = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sql-delight" }
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
#test
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-plugin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-couroutine" }
mokkery = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
all-open = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin-plugin" }

[plugins]
#convention->
convention-maven = { id = "com.tezov.tuucho.convention.project.maven", version = "" }
convention-library-test = { id = "com.tezov.tuucho.convention.project.library-test", version = "" }
convention-library-plain = { id = "com.tezov.tuucho.convention.project.library-plain", version = "" }
convention-library-ui = { id = "com.tezov.tuucho.convention.project.library-ui", version = "" }
#<-convention
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-plugin" }
kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-plugin" }
koin = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-plugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization-plugin" }
sql-delight = { id = "app.cash.sqldelight", version.ref = "sql-delight" }
maven = { id = "maven-publish", version = "" }
signing = { id = "signing", version = "" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt-plugin" }
#test
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
all-open = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin-plugin" }
