[versions]
#convention
domain = "com.tezov"
name = "tuucho.sample"
keystorePropertiesFilePath = "keystore.properties"
versionCode = "1"
versionName = "0.0.1-alpha23_2.3.0"
javaVersion = "17"
minSdk = "24"
targetSdk = "36"
compileSdk = "36"

#plugin
android-plugin = "8.13.2"
kotlin-plugin = "2.3.0"
compose-plugin = "1.9.3"
build-konfig-plugin = "0.17.1"

#lib - android
compose = "1.10.0"
compose-activity = "1.12.2"

#lib - platform
kermit = "2.0.8"
ktor = "3.3.3"
koin = "4.2.0-beta2"
kotlin-serialization-json = "1.9.0"

[libraries]
#build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
#tuucho
tuucho = { group = "com.tezov", name = "tuucho.core", version.ref = "versionName" }
tuucho-android = { group = "com.tezov", name = "tuucho.core-android", version.ref = "versionName" }
#compose - android
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
#lib - platform
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
#lib - android
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
#lib - ios
ktor-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
[plugins]
#convention
convention-application-android = { id = "com.tezov.tuucho.convention.application-android", version = "unspecified" }
convention-application-ios = { id = "com.tezov.tuucho.convention.application-ios", version = "unspecified" }
convention-shared-library = { id = "com.tezov.tuucho.convention.shared-library", version = "unspecified" }
#convention
build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "build-konfig-plugin" }
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-plugin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
